import qrcode
from io import BytesIO
import base64
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from datetime import datetime
import uuid

def generate_qr_code(data: str) -> str:
    """Generate QR code and return as base64 string"""
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data(data)
    qr.make(fit=True)
    
    img = qr.make_image(fill_color="black", back_color="white")
    buffered = BytesIO()
    img.save(buffered, format="PNG")
    img_str = base64.b64encode(buffered.getvalue()).decode()
    return img_str

def generate_certificate_pdf(student_name: str, event_title: str, event_date: str) -> str:
    """Generate certificate PDF and return as base64 string"""
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    
    # Draw border
    c.setStrokeColor(colors.HexColor('#5E35B1'))
    c.setLineWidth(3)
    c.rect(0.5*inch, 0.5*inch, width-inch, height-inch)
    
    # Inner border
    c.setStrokeColor(colors.HexColor('#42A5F5'))
    c.setLineWidth(1)
    c.rect(0.6*inch, 0.6*inch, width-1.2*inch, height-1.2*inch)
    
    # Title
    c.setFont("Helvetica-Bold", 36)
    c.setFillColor(colors.HexColor('#5E35B1'))
    c.drawCentredString(width/2, height-2*inch, "CERTIFICATE")
    
    # Subtitle
    c.setFont("Helvetica", 18)
    c.setFillColor(colors.HexColor('#42A5F5'))
    c.drawCentredString(width/2, height-2.5*inch, "OF PARTICIPATION")
    
    # This is to certify
    c.setFont("Helvetica", 14)
    c.setFillColor(colors.black)
    c.drawCentredString(width/2, height-3.5*inch, "This is to certify that")
    
    # Student name
    c.setFont("Helvetica-Bold", 24)
    c.setFillColor(colors.HexColor('#EC407A'))
    c.drawCentredString(width/2, height-4.2*inch, student_name)
    
    # Event details
    c.setFont("Helvetica", 14)
    c.setFillColor(colors.black)
    c.drawCentredString(width/2, height-5*inch, "has successfully participated in")
    
    c.setFont("Helvetica-Bold", 18)
    c.setFillColor(colors.HexColor('#5E35B1'))
    c.drawCentredString(width/2, height-5.7*inch, event_title)
    
    # Date
    c.setFont("Helvetica", 12)
    c.setFillColor(colors.black)
    c.drawCentredString(width/2, height-6.4*inch, f"held on {event_date}")
    
    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawCentredString(width/2, 1.5*inch, "Generated by JoinUp - Digital Event Platform")
    
    # Issue date
    c.setFont("Helvetica", 10)
    c.drawString(inch, inch, f"Issued: {datetime.now().strftime('%B %d, %Y')}")
    
    # Certificate ID
    cert_id = str(uuid.uuid4())[:8].upper()
    c.drawRightString(width-inch, inch, f"Certificate ID: {cert_id}")
    
    c.save()
    pdf_data = buffer.getvalue()
    buffer.close()
    
    return base64.b64encode(pdf_data).decode()
